### ISSUE TITLE
Add removeTreeNode methods to AvlTree and BinarySearchTree

### ISSUE THREAD

**Issue by masx200** [datastructures-js/binary-search-tree#57]
Add removeTreeNode methods to AvlTree and BinarySearchTree

https://github.com/datastructures-js/binary-search-tree/blob/bcc16da46641286bc1e507ac5defa49d11a30a99/src/avlTree.d.ts#L4

https://github.com/datastructures-js/binary-search-tree/blob/master/src/avlTree.d.ts#L4

https://github.com/denoland/deno_std/issues/3055

A node can be removed from a binary tree with O(1) time complexity using the removeTreeNode method.

https://cplusplus.com/reference/set/set/erase/

**Comment by eyas-ranjous** [comment]
@masx200 

After reviewing this feature, there is an important finding here about removeNode. I do not see how it can be a perfect O(1). because your analysis did not take in consideration the worse case scenario of when the to-be-removed node, has both a left and right children. meaning, we have to find the node with min value in the right sub-tree, this operation itself is an O(log(n)) in the worst case, the method removeNode can still be added though, I like it, but you are aware about this case, what's you take on it?

https://github.com/datastructures-js/binary-search-tree/blob/master/src/binarySearchTree.js#L306-L309

**Comment by masx200** [comment]
For example, when I want to traverse the binary search tree from large to small and delete the largest nodes, I should first do reverse mid-order traversal, and then delete the nodes directly to speed up.

**Comment by eyas-ranjous** [comment]
right, but you agree that worst case scenario of the function is O(log(n)) correct?
